summon cr:mine_explosion ~1~~
summon cr:mine_explosion ~2~~
summon cr:mine_explosion ~~~1
summon cr:mine_explosion ~~~2
summon cr:mine_explosion ~1~~1
summon cr:mine_explosion ~2~~2
summon cr:mine_explosion ~2~~1
summon cr:mine_explosion ~1~~2
summon cr:mine_explosion ~1~~-1
summon cr:mine_explosion ~2~~-2
summon cr:mine_explosion ~2~~-1
summon cr:mine_explosion ~1~~-2
summon cr:mine_explosion ~~~-1
summon cr:mine_explosion ~~~-2
summon cr:mine_explosion ~-1~~
summon cr:mine_explosion ~-2~~
summon cr:mine_explosion ~-1~~1
summon cr:mine_explosion ~-2~~2
summon cr:mine_explosion ~-2~~1
summon cr:mine_explosion ~-1~~2
summon cr:mine_explosion ~-1~~-1
summon cr:mine_explosion ~-2~~-2
summon cr:mine_explosion ~-2~~-1
summon cr:mine_explosion ~-1~~-2
summon cr:mine_explosion ~~2~
summon cr:mine_explosion ~~3~
summon cr:mine_explosion ~1~1~
summon cr:mine_explosion ~2~1~
summon cr:mine_explosion ~~1~1
summon cr:mine_explosion ~~1~2
summon cr:mine_explosion ~1~1~1
summon cr:mine_explosion ~2~1~2
summon cr:mine_explosion ~2~1~1
summon cr:mine_explosion ~1~1~2
summon cr:mine_explosion ~1~1~-1
summon cr:mine_explosion ~2~1~-2
summon cr:mine_explosion ~2~1~-1
summon cr:mine_explosion ~1~1~-2
summon cr:mine_explosion ~~1~-1
summon cr:mine_explosion ~~1~-2
summon cr:mine_explosion ~-1~1~
summon cr:mine_explosion ~-2~1~
summon cr:mine_explosion ~-1~1~1
summon cr:mine_explosion ~-2~1~2
summon cr:mine_explosion ~-2~1~1
summon cr:mine_explosion ~-1~1~2
summon cr:mine_explosion ~-1~1~-1
summon cr:mine_explosion ~-2~1~-2
summon cr:mine_explosion ~-2~1~-1
summon cr:mine_explosion ~-1~1~-2
summon cr:mine_explosion ~1~2~
summon cr:mine_explosion ~2~2~
summon cr:mine_explosion ~~2~1
summon cr:mine_explosion ~~2~2
summon cr:mine_explosion ~1~2~1
summon cr:mine_explosion ~2~2~2
summon cr:mine_explosion ~2~2~1
summon cr:mine_explosion ~1~2~2
summon cr:mine_explosion ~1~2~-1
summon cr:mine_explosion ~2~2~-2
summon cr:mine_explosion ~2~2~-1
summon cr:mine_explosion ~1~2~-2
summon cr:mine_explosion ~~2~-1
summon cr:mine_explosion ~~2~-2
summon cr:mine_explosion ~-1~2~
summon cr:mine_explosion ~-2~2~
summon cr:mine_explosion ~-1~2~1
summon cr:mine_explosion ~-2~2~2
summon cr:mine_explosion ~-2~2~1
summon cr:mine_explosion ~-1~2~2
summon cr:mine_explosion ~-1~2~-1
summon cr:mine_explosion ~-2~2~-2
summon cr:mine_explosion ~-2~2~-1
summon cr:mine_explosion ~-1~2~-2
summon cr:mine_explosion ~~-1~
summon cr:mine_explosion ~~-1~-1
summon cr:mine_explosion ~~-1~-2
summon cr:mine_explosion ~~-1~-3
summon cr:mine_explosion ~1~-1~
summon cr:mine_explosion ~2~-1~
summon cr:mine_explosion ~~-1~1
summon cr:mine_explosion ~~-1~2
summon cr:mine_explosion ~1~-1~1
summon cr:mine_explosion ~2~-1~2
summon cr:mine_explosion ~2~-1~1
summon cr:mine_explosion ~1~-1~2
summon cr:mine_explosion ~1~-1~-1
summon cr:mine_explosion ~2~-1~-2
summon cr:mine_explosion ~2~-1~-1
summon cr:mine_explosion ~1~-1~-2
summon cr:mine_explosion ~~-2~-1
summon cr:mine_explosion ~~-2~-2
summon cr:mine_explosion ~-1~-1~
summon cr:mine_explosion ~-2~-1~
summon cr:mine_explosion ~-1~-1~1
summon cr:mine_explosion ~-2~-1~2
summon cr:mine_explosion ~-2~-1~1
summon cr:mine_explosion ~-1~-1~2
summon cr:mine_explosion ~-1~-1~-1
summon cr:mine_explosion ~-2~-1~-2
summon cr:mine_explosion ~-2~-1~-1
summon cr:mine_explosion ~-1~-1~-2
summon cr:mine_explosion ~~-2~
summon cr:mine_explosion ~~-2~-1
summon cr:mine_explosion ~~-2~-2
summon cr:mine_explosion ~~-2~-3
summon cr:mine_explosion ~1~-2~
summon cr:mine_explosion ~2~-2~
summon cr:mine_explosion ~~-2~1
summon cr:mine_explosion ~~-2~2
summon cr:mine_explosion ~1~-2~1
summon cr:mine_explosion ~2~-2~2
summon cr:mine_explosion ~2~-2~1
summon cr:mine_explosion ~1~-2~2
summon cr:mine_explosion ~1~-2~-1
summon cr:mine_explosion ~2~-2~-2
summon cr:mine_explosion ~2~-2~-1
summon cr:mine_explosion ~1~-2~-2
summon cr:mine_explosion ~~-2~-1
summon cr:mine_explosion ~~-2~-2
summon cr:mine_explosion ~-1~-2~
summon cr:mine_explosion ~-2~-2~
summon cr:mine_explosion ~-1~-2~1
summon cr:mine_explosion ~-2~-2~2
summon cr:mine_explosion ~-2~-2~1
summon cr:mine_explosion ~-1~-2~2
summon cr:mine_explosion ~-1~-2~-1
summon cr:mine_explosion ~-2~-2~-2
summon cr:mine_explosion ~-2~-2~-1
summon cr:mine_explosion ~-1~-2~-2