summon cr:mine_explosion ~~2~
summon cr:mine_explosion ~~~1
summon cr:mine_explosion ~~~-1
summon cr:mine_explosion ~~1~
summon cr:mine_explosion ~1~~
summon cr:mine_explosion ~-1~~
summon cr:mine_explosion ~~1~1
summon cr:mine_explosion ~~1~-1
summon cr:mine_explosion ~1~1~
summon cr:mine_explosion ~-1~1~
summon cr:mine_explosion ~~2~1
summon cr:mine_explosion ~~2~-1
summon cr:mine_explosion ~1~2~
summon cr:mine_explosion ~-1~2~
summon cr:mine_explosion ~1~~1
summon cr:mine_explosion ~-1~~-1
summon cr:mine_explosion ~1~~-1
summon cr:mine_explosion ~-1~~1
summon cr:mine_explosion ~1~1~1
summon cr:mine_explosion ~-1~1~-1
summon cr:mine_explosion ~1~1~-1
summon cr:mine_explosion ~-1~1~1
summon cr:mine_explosion ~1~2~1
summon cr:mine_explosion ~-1~2~-1
summon cr:mine_explosion ~1~2~-1
summon cr:mine_explosion ~-1~2~1